name: "test-rtsmith"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Cancel any preceding run on the pull request.
concurrency:
  group: test-rtsmith-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  # Build and test P4RuntimeSmith on Ubuntu 22.04.
  build-and-test-rtsmith:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    env:
      CTEST_PARALLEL_LEVEL: 4
      IMAGE_TYPE: test
      CMAKE_UNITY_BUILD: ON
      ENABLE_TEST_TOOLS: ON
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: test-flay-${{ runner.os }}
        max-size: 1000M

    - name: Pull P4C and link P4RuntimeSmith.
      run: |
        git clone --recurse-submodules -j2 https://github.com/p4lang/p4c/ $GITHUB_WORKSPACE/../p4c
        ln -sf $GITHUB_WORKSPACE $GITHUB_WORKSPACE/../p4c/backends/p4tools/modules/

    - name: Build (Ubuntu 22.04)
      run: |
        tools/ci-build.sh
      working-directory: ../p4c

